/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TcfWaiverRouteImport } from './routes/tcf-waiver'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnimalsRouteImport } from './routes/animals'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsRabbitRouteImport } from './routes/programs.rabbit'
import { Route as ProgramsPoultryRouteImport } from './routes/programs.poultry'
import { Route as ProgramsHorseRouteImport } from './routes/programs.horse'
import { Route as ProgramsGoatRouteImport } from './routes/programs.goat'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TcfWaiverRoute = TcfWaiverRouteImport.update({
  id: '/tcf-waiver',
  path: '/tcf-waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimalsRoute = AnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsRabbitRoute = ProgramsRabbitRouteImport.update({
  id: '/rabbit',
  path: '/rabbit',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsPoultryRoute = ProgramsPoultryRouteImport.update({
  id: '/poultry',
  path: '/poultry',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsHorseRoute = ProgramsHorseRouteImport.update({
  id: '/horse',
  path: '/horse',
  getParentRoute: () => ProgramsRoute,
} as any)
const ProgramsGoatRoute = ProgramsGoatRouteImport.update({
  id: '/goat',
  path: '/goat',
  getParentRoute: () => ProgramsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/animals': typeof AnimalsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tcf-waiver': typeof TcfWaiverRoute
  '/volunteer': typeof VolunteerRoute
  '/programs/goat': typeof ProgramsGoatRoute
  '/programs/horse': typeof ProgramsHorseRoute
  '/programs/poultry': typeof ProgramsPoultryRoute
  '/programs/rabbit': typeof ProgramsRabbitRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/animals': typeof AnimalsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tcf-waiver': typeof TcfWaiverRoute
  '/volunteer': typeof VolunteerRoute
  '/programs/goat': typeof ProgramsGoatRoute
  '/programs/horse': typeof ProgramsHorseRoute
  '/programs/poultry': typeof ProgramsPoultryRoute
  '/programs/rabbit': typeof ProgramsRabbitRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/animals': typeof AnimalsRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tcf-waiver': typeof TcfWaiverRoute
  '/volunteer': typeof VolunteerRoute
  '/programs/goat': typeof ProgramsGoatRoute
  '/programs/horse': typeof ProgramsHorseRoute
  '/programs/poultry': typeof ProgramsPoultryRoute
  '/programs/rabbit': typeof ProgramsRabbitRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/animals'
    | '/contact'
    | '/donate'
    | '/events'
    | '/login'
    | '/programs'
    | '/sitemap.xml'
    | '/tcf-waiver'
    | '/volunteer'
    | '/programs/goat'
    | '/programs/horse'
    | '/programs/poultry'
    | '/programs/rabbit'
    | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/animals'
    | '/contact'
    | '/donate'
    | '/events'
    | '/login'
    | '/sitemap.xml'
    | '/tcf-waiver'
    | '/volunteer'
    | '/programs/goat'
    | '/programs/horse'
    | '/programs/poultry'
    | '/programs/rabbit'
    | '/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/animals'
    | '/contact'
    | '/donate'
    | '/events'
    | '/login'
    | '/programs'
    | '/sitemap.xml'
    | '/tcf-waiver'
    | '/volunteer'
    | '/programs/goat'
    | '/programs/horse'
    | '/programs/poultry'
    | '/programs/rabbit'
    | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnimalsRoute: typeof AnimalsRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TcfWaiverRoute: typeof TcfWaiverRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tcf-waiver': {
      id: '/tcf-waiver'
      path: '/tcf-waiver'
      fullPath: '/tcf-waiver'
      preLoaderRoute: typeof TcfWaiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animals': {
      id: '/animals'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AnimalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/rabbit': {
      id: '/programs/rabbit'
      path: '/rabbit'
      fullPath: '/programs/rabbit'
      preLoaderRoute: typeof ProgramsRabbitRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/poultry': {
      id: '/programs/poultry'
      path: '/poultry'
      fullPath: '/programs/poultry'
      preLoaderRoute: typeof ProgramsPoultryRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/horse': {
      id: '/programs/horse'
      path: '/horse'
      fullPath: '/programs/horse'
      preLoaderRoute: typeof ProgramsHorseRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/programs/goat': {
      id: '/programs/goat'
      path: '/goat'
      fullPath: '/programs/goat'
      preLoaderRoute: typeof ProgramsGoatRouteImport
      parentRoute: typeof ProgramsRoute
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsGoatRoute: typeof ProgramsGoatRoute
  ProgramsHorseRoute: typeof ProgramsHorseRoute
  ProgramsPoultryRoute: typeof ProgramsPoultryRoute
  ProgramsRabbitRoute: typeof ProgramsRabbitRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsGoatRoute: ProgramsGoatRoute,
  ProgramsHorseRoute: ProgramsHorseRoute,
  ProgramsPoultryRoute: ProgramsPoultryRoute,
  ProgramsRabbitRoute: ProgramsRabbitRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnimalsRoute: AnimalsRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TcfWaiverRoute: TcfWaiverRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
